---
# Styled-components docs
# - https://www.styled-components.com/docs/tooling#stylelint
#
# Principles of writing consistent, idiomatic CSS
#  - https://github.com/necolas/idiomatic-css {
ignoreFiles:
- node_modules/**/*
- dist/**/*
processors:
- stylelint-processor-styled-components
extends:
- stylelint-config-recommended
- stylelint-config-styled-components
plugins:
- stylelint-order
rules:
  font-family-name-quotes: always-where-recommended
  function-url-quotes: always
  selector-attribute-quotes: always
  string-quotes: double
  order/properties-order:
  # Display
  - display
  - visibility
  - opacity
  - list-style
  - list-style-type
  - list-style-position
  - list-style-image
  # Position
  - positoin
  - top
  - right
  - bottom
  - left
  - z-index
  - float
  - clear
  - transform
  - transform-box
  - transform-origin
  - transform-style
  # Box Model
  - width
  - min-width
  - max-width
  - height
  - min-height
  - max-height
  - margin
  - margin-top
  - margin-right
  - margin-bottom
  - margin-left
  - padding
  - padding-top
  - padding-right
  - padding-bottom
  - padding-left
  - overflow
  - overflow-x
  - overflow-y
  - border
  - border-top
  - border-right
  - border-bottom
  - border-left
  - border-width
  - border-top-width
  - border-right-width
  - border-bottom-width
  - border-left-width
  - border-style
  - border-top-style
  - border-right-style
  - border-bottom-style
  - border-left-style
  - border-radius
  - border-top-left-radius
  - border-top-right-radius
  - border-bottom-left-radius
  - border-bottom-right-radius
  - border-color
  - border-top-color
  - border-right-color
  - border-bottom-color
  - border-left-color
  - border-image
  - border-top-image
  - border-right-image
  - border-bottom-image
  - border-left-image
  - box-sizing
  - box-shadow
  # Background
  - background
  - background-attachment
  - background-clip
  - background-color
  - background-image
  - background-repeat
  - background-position
  - background-size
  - background-origin
  - fill
  # Font, Text and Color
  - color
  - font
  - font-family
  - font-size
  - font-smoothing
  - font-style
  - font-variant
  - font-weight
  - line-height
  - letter-spacing
  - text-align
  - text-decoration
  - text-decoration-color
  - text-decoration-style
  - text-decoration-line
  - text-indent
  - text-overflow
  - text-rendering
  - text-shadow
  - text-transform
  - text-wrap
  - white-space
  - word-break
  - word-spacing
  - word-wrap
  - text-shadow
  # Table
  - table-layout
  - border-collapse
  - border-spacing
  - empty-cells
  - caption-side
  - vertical-align
  # Flexbox
  - flex
  - flex-grow
  - flex-shrink
  - flex-basis
  - flex-flow
  - flex-direction
  - flex-wrap
  - justify-content
  - align-content
  - align-items
  - align-self
  - order
  # User Interface
  - content
  - quotes
  - conter-increment
  - conter-reset
  - outline
  - outline-color
  - outline-offset
  - outline-style
  - outline-width
  - resize
  - speak
  # Cursor
  - cursor
  - pointer-events
  - user-select
  - appearance
  # Multi Columns
  - columns
  - column-count
  - column-gap
  - column-fill
  - column-rule
  - column-span
  - column-width
  - grid-gap
  - grid-template-columns
  # Animation
  - animation
  - animation-name
  - animation-timing-function
  - transition
  - transition-delay
  - transition-duration
  - transition-property
  - transition-timing-function
  - will-change
  declaration-property-unit-whitelist:
    font-size:
      - "px"
      - "rem"
    /^animation/:
      - "s"
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true
  property-no-unknown:
    - true
  selector-max-id: 0
  selector-no-qualifying-type: true
  font-weight-notation: named-where-possible
  function-url-no-scheme-relative: true
  comment-word-blacklist:
    -
      - /^TODO:/
      - /^FIXME:/
    - severity: warning
  number-leading-zero: never
